#!/usr/bin/perl

# File generated by menutray v0.52

# DO NOT edit this file!
# Any change in this file will be lost!
# Edit ~/.config/menutray/schema.pl instead!

use utf8;
use strict;
use Gtk2 ('-init');

my $menu = 'Gtk2::Menu'->new;
my $icon = 'Gtk2::StatusIcon'->new;

my $menutray_title   = "menutray";
my $menutray_tooltip = "Applications";

if (defined($menutray_title) and 1) {
    $icon->set_title($menutray_title);
    $icon->set_name('');
}

if (defined($menutray_tooltip) and 1) {
    $icon->set_tooltip($menutray_tooltip);
}

$icon->set_from_icon_name('start-here');
$icon->set_visible(1);
$icon->signal_connect('button-release-event', \&show_icon_menu);

local $SIG{USR1} = \&show_icon_menu;

load_menu();

sub show_icon_menu {
    my (undef, $event) = @_;

    if (ref($event) and $event->button == 3) {

        my $right_click = 'Gtk2::Menu'->new;
        {
            my $regenerate = 'Gtk2::ImageMenuItem'->new("_Regenerate");
            $regenerate->set_property('tooltip_text', "Regenerate\ this\ menu\.");
            $regenerate->set_image('Gtk2::Image'->new_from_icon_name("gtk\-refresh",q{menu}));
            $regenerate->signal_connect('activate', sub {system "\/usr\/bin\/perl\ \\\/usr\\\/bin\\\/menutray\ \-i\ \-C\ \\\/home\\\/pi\\\/\\\.config\\\/menutray\\\/config\\\.pl\ \-S\ \\\/home\\\/pi\\\/\\\.config\\\/menutray\\\/schema\\\.pl\ \-o\ \\\/home\\\/pi\\\/\\\.config\\\/menutray\\\/menu\\\.pl &"; 'Gtk2'->main_quit});
            \$right_click->append($regenerate);
        }

        {
            my $quit = 'Gtk2::ImageMenuItem'->new("_Quit");
            $quit->set_property('tooltip_text', "Close\ this\ application\.");
            $quit->set_image('Gtk2::Image'->new_from_icon_name("application\-exit",q{menu}));
            $quit->signal_connect('activate', sub { 'Gtk2'->main_quit });
            \$right_click->append($quit);
        }

        $right_click->show_all;
        $right_click->popup(undef, undef, sub {
            my ($x, $y, @list) = Gtk2::StatusIcon::position_menu($right_click, 0, 0, $icon);
            ($x, $y) = @_[1,2] if 0;
            ($x, $y, @list);
        }, [1, 1], 0, 0);

        return 1;
    }
    $menu->popup(undef, undef, sub {
            my ($x, $y, @list) = Gtk2::StatusIcon::position_menu($menu, 0, 0, $icon);
            ($x, $y) = @_[1,2] if 0;
            ($x, $y, @list);
        }, [1, 1], 0, 0);

    return 1;
}

sub load_menu {
{
    my $item = 'Gtk2::ImageMenuItem'->new("_Файлы");
    $item->set_image('Gtk2::Image'->new_from_icon_name("system\-file\-manager",q{menu}));
    $item->signal_connect('activate', sub {system "xdg\-open\ \. &"});
    $menu->append($item);
}

{
    my $item = 'Gtk2::ImageMenuItem'->new("_Терминал");
    $item->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $item->signal_connect('activate', sub {system "terminator &"});
    $menu->append($item);
}

{
    my $item = 'Gtk2::ImageMenuItem'->new("_Браузер");
    $item->set_image('Gtk2::Image'->new_from_icon_name("web\-browser",q{menu}));
    $item->signal_connect('activate', sub {system "xdg\-open\ http\:\/\/www\.google\.com &"});
    $menu->append($item);
}

{
    my $item = 'Gtk2::ImageMenuItem'->new("_Выполнить\ команду");
    $item->set_image('Gtk2::Image'->new_from_icon_name("system\-run",q{menu}));
    $item->signal_connect('activate', sub {system "gmrun &"});
    $menu->append($item);
}


    $menu->append('Gtk2::SeparatorMenuItem'->new);

    # # # # # # # # # # # # # # # # # # # # Ð¡ÑÐ°Ð½Ð´Ð°ÑÑÐ½ÑÐΜ # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("_Стандартные");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-utilities",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("_compton");
    $app->signal_connect('activate', sub {system "compton &"});
    $app->set_property('tooltip_text', "Compositor\ for\ X11");
    $app->set_image('Gtk2::Image'->new_from_icon_name("compton",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Leafpad");
    $app->signal_connect('activate', sub {system "leafpad &"});
    $app->set_property('tooltip_text', "Простой\ текстовый\ редактор");
    $app->set_image('Gtk2::Image'->new_from_icon_name("leafpad",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_nitrogen");
    $app->signal_connect('activate', sub {system "nitrogen &"});
    $app->set_property('tooltip_text', "Просмотр\ и\ выбор\ фонов\ рабочих\ столов");
    $app->set_image('Gtk2::Image'->new_from_icon_name("nitrogen",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Vim");
    $app->signal_connect('activate', sub {system "terminator\ \-e\ \'vim\' &"});
    $app->set_property('tooltip_text', "Редактор\ текстовых\ файлов");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gvim",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Терминатор");
    $app->signal_connect('activate', sub {system "terminator &"});
    $app->set_property('tooltip_text', "Несколько\ терминалов\ в\ одном\ окне");
    $app->set_image('Gtk2::Image'->new_from_icon_name("terminator",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Файловый\ менеджер\ PCManFM");
    $app->signal_connect('activate', sub {system "pcmanfm &"});
    $app->set_property('tooltip_text', "Просмотр\ файловой\ системы\ и\ управление\ файлами");
    $app->set_image('Gtk2::Image'->new_from_icon_name("system\-file\-manager",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # Ð Ð°Ð·ÑÐ°Ð±Ð¾ÑÐºÐ° # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("_Разработка");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-development",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("_CMake");
    $app->signal_connect('activate', sub {system "cmake\-gui &"});
    $app->set_property('tooltip_text', "Cross\-platform\ buildsystem");
    $app->set_image('Gtk2::Image'->new_from_icon_name("CMakeSetup",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Geany");
    $app->signal_connect('activate', sub {system "geany &"});
    $app->set_property('tooltip_text', "Быстрая\ и\ легковесная\ среда\ разработки\,\ использующая\ GTK\+");
    $app->set_image('Gtk2::Image'->new_from_icon_name("geany",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Qt4\ Assistant");
    $app->signal_connect('activate', sub {system "assistant\-qt4 &"});
    $app->set_property('tooltip_text', "Shows\ Qt4\ documentation\ and\ examples");
    $app->set_image('Gtk2::Image'->new_from_icon_name("assistant\-qt4",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Qt4\ Designer");
    $app->signal_connect('activate', sub {system "designer\-qt4 &"});
    $app->set_property('tooltip_text', "Design\ GUIs\ for\ Qt4\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("designer\-qt4",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Qt4\ Linguist");
    $app->signal_connect('activate', sub {system "linguist\-qt4 &"});
    $app->set_property('tooltip_text', "Add\ translations\ to\ Qt4\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("linguist\-qt4",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Qt4\ QDbusViewer");
    $app->signal_connect('activate', sub {system "qdbusviewer\-qt4 &"});
    $app->set_property('tooltip_text', "Debug\ D\-Bus\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("qdbusviewer\-qt4",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # ÐÑÐ°ÑÐ¸ÐºÐ° # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("_Графика");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-graphics",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Viewnior");
    $app->signal_connect('activate', sub {system "viewnior &"});
    $app->set_property('tooltip_text', "Изящный\ просмотрщик\ изображений");
    $app->set_image('Gtk2::Image'->new_from_icon_name("viewnior",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # ÐÑÐ»ÑÑÐ¸Ð¼ÐΜÐ´Ð¸Ð° # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("_Мультимедиа");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-multimedia",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Регулятор\ громкости\ PulseAudio");
    $app->signal_connect('activate', sub {system "pavucontrol &"});
    $app->set_property('tooltip_text', "Настройка\ уровня\ громкости");
    $app->set_image('Gtk2::Image'->new_from_icon_name("multimedia\-volume\-control",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # Ð¡ÐΜÑÑ # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("_Сеть");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-internet",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Midori");
    $app->signal_connect('activate', sub {system "midori &"});
    $app->set_property('tooltip_text', "Работа\ в\ Интернете");
    $app->set_image('Gtk2::Image'->new_from_icon_name("midori",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Transmission");
    $app->signal_connect('activate', sub {system "transmission\-gtk &"});
    $app->set_property('tooltip_text', "Загружайте\ и\ обменивайтесь\ файлами\ в\ сети\ BitTorrent");
    $app->set_image('Gtk2::Image'->new_from_icon_name("transmission",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Навигатор\ Avahi\ по\ серверам\ SSH");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/bssh &"});
    $app->set_property('tooltip_text', "Просмотр\ списка\ серверов\ SSH\ с\ включённой\ службой\ Zeroconf");
    $app->set_image('Gtk2::Image'->new_from_icon_name("network\-wired",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Навигатор\ Avahi\ по\ серверам\ VNC");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/bvnc &"});
    $app->set_property('tooltip_text', "Просмотр\ списка\ серверов\ VNC\ с\ включённой\ службой\ Zeroconf");
    $app->set_image('Gtk2::Image'->new_from_icon_name("network\-wired",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # ÐÑÐ¸Ñ # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("_Офис");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-office",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("_ePDFViewer");
    $app->signal_connect('activate', sub {system "epdfview &"});
    $app->set_property('tooltip_text', "Lightweight\ PDF\ document\ viewer");
    $app->set_image('Gtk2::Image'->new_from_icon_name("epdfview",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_FBReader");
    $app->signal_connect('activate', sub {system "FBReader &"});
    $app->set_property('tooltip_text', "FBReader\,\ программа\ для\ чтения\ электронных\ книг");
    $app->set_image('Gtk2::Image'->new_from_icon_name("FBReader",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # ÐÐ°ÑÑÑÐ¾Ð¹ÐºÐ¸ # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("_Настройки");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-accessories",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Настройка\ внешнего\ вида");
    $app->signal_connect('activate', sub {system "lxappearance &"});
    $app->set_property('tooltip_text', "Настройте\ тему\ рабочего\ стола\ и\ приложений");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop\-theme",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Параметры\ рабочего\ стола");
    $app->signal_connect('activate', sub {system "pcmanfm\ \-\-desktop\-pref &"});
    $app->set_property('tooltip_text', "Смена\ обоев\ рабочего\ стола\ и\ поведения\ менеджера\ рабочего\ стола");
    $app->set_image('Gtk2::Image'->new_from_icon_name("user\-desktop",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Предпочтительные\ приложения");
    $app->signal_connect('activate', sub {system "libfm\-pref\-apps &"});
    $app->set_property('tooltip_text', "Выбрать\ приложения\,\ открываемые\ при\ клике\ на\ Web\-ссылку\ или\ адрес\ почты");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # Ð¡Ð¸ÑÑÐΜÐ¼Ð° # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("_Система");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-system",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Htop");
    $app->signal_connect('activate', sub {system "terminator\ \-e\ \'htop\' &"});
    $app->set_property('tooltip_text', "Просмотр\ списка\ процессов\ в\ системе");
    $app->set_image('Gtk2::Image'->new_from_icon_name("htop",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_jgmenu");
    $app->signal_connect('activate', sub {system "jgmenu_run &"});
    $app->set_property('tooltip_text', "Отображает\ меню\ для\ запуска\ установленных\ приложений");
    $app->set_image('Gtk2::Image'->new_from_icon_name("jgmenu",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_LSHW");
    $app->signal_connect('activate', sub {system "\/usr\/sbin\/gtk\-lshw &"});
    $app->set_property('tooltip_text', "HardWare\ LiSter");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/lshw\/artwork\/logo\.svg",16,16)));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_UXTerm");
    $app->signal_connect('activate', sub {system "uxterm &"});
    $app->set_property('tooltip_text', "xterm\ wrapper\ for\ Unicode\ environments");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xterm\-color_48x48",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_XTerm");
    $app->signal_connect('activate', sub {system "xterm &"});
    $app->set_property('tooltip_text', "standard\ terminal\ emulator\ for\ the\ X\ window\ system");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xterm\-color_48x48",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Обозреватель\ Avahi\ Zeroconf");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/avahi\-discover &"});
    $app->set_property('tooltip_text', "Поиск\ служб\ Zeroconf\ в\ локальной\ сети");
    $app->set_image('Gtk2::Image'->new_from_icon_name("network\-wired",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Терминатор");
    $app->signal_connect('activate', sub {system "terminator &"});
    $app->set_property('tooltip_text', "Несколько\ терминалов\ в\ одном\ окне");
    $app->set_image('Gtk2::Image'->new_from_icon_name("terminator",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Файловый\ менеджер\ PCManFM");
    $app->signal_connect('activate', sub {system "pcmanfm &"});
    $app->set_property('tooltip_text', "Просмотр\ файловой\ системы\ и\ управление\ файлами");
    $app->set_image('Gtk2::Image'->new_from_icon_name("system\-file\-manager",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # MENUTRAY # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("_Menutray");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Config");
    $app->signal_connect('activate', sub {system "geany\ \\\/home\\\/pi\\\/\\\.config\\\/menutray\\\/config\\\.pl &"});
    $app->set_property('tooltip_text', "Open\ the\ configuration\ file");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gtk\-edit",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Menu");
    $app->signal_connect('activate', sub {system "geany\ \\\/home\\\/pi\\\/\\\.config\\\/menutray\\\/menu\\\.pl &"});
    $app->set_property('tooltip_text', "Open\ the\ menu\ file\ for\ inspection");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gtk\-edit",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Schema");
    $app->signal_connect('activate', sub {system "geany\ \\\/home\\\/pi\\\/\\\.config\\\/menutray\\\/schema\\\.pl &"});
    $app->set_property('tooltip_text', "Open\ the\ schema\ file\ to\ customize\ the\ menu");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gtk\-edit",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    $menu->append('Gtk2::SeparatorMenuItem'->new);
{
    my $regenerate = 'Gtk2::ImageMenuItem'->new("_Обновить\ меню");
    $regenerate->set_property('tooltip_text', "Regenerate\ this\ menu\.");
    $regenerate->set_image('Gtk2::Image'->new_from_icon_name("gtk\-refresh",q{menu}));
    $regenerate->signal_connect('activate', sub {system "\/usr\/bin\/perl\ \\\/usr\\\/bin\\\/menutray\ \-i\ \-C\ \\\/home\\\/pi\\\/\\\.config\\\/menutray\\\/config\\\.pl\ \-S\ \\\/home\\\/pi\\\/\\\.config\\\/menutray\\\/schema\\\.pl\ \-o\ \\\/home\\\/pi\\\/\\\.config\\\/menutray\\\/menu\\\.pl &"; 'Gtk2'->main_quit});
    $menu->append($regenerate);
}

    $menu->append('Gtk2::SeparatorMenuItem'->new);
{
    my $item = 'Gtk2::ImageMenuItem'->new("_Выключение");
    $item->set_image('Gtk2::Image'->new_from_icon_name("system\-run",q{menu}));
    $item->signal_connect('activate', sub {system "gmrun &"});
    $menu->append($item);
}

    $menu->show_all;
    return 1;
}
'Gtk2'->main;
